export enum routes {
  ONBOARD = 'ONBOARD',
  LOBBY = 'LOBBY',
  SIGN_IN = 'SIGN_IN',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',

  BOTTOM_TAB = 'BOTTOM_TAB',
  HOME = 'HOME',
  SAVE_JOB = 'SAVE_JOB',
  PROFILE = 'PROFILE',
  MESSAGES = 'MESSAGES',
  APPLICATIONS = 'APPLICATIONS',
  SOCIAL = 'SOCIAL',

  //in home
  NOTIFICATION = 'NOTIFICATION',
  SEARCH = 'SEARCH',
  JOB_DETAIL = 'JOB_DETAIL',
  APPLY_PROFILE = 'APPLY_PROFILE',
  APPLY_CV = 'APPLY_CV',
  //in application
  STATUS_APPLICATION = 'STATUS_APPLICATION',
  HISTORY_APPLICATION = 'HISTORY_APPLICATION',
  REQUEST_APPLICATION = 'REQUEST_APPLICATION',
  POST_JOB_APPLICATION = 'POST_JOB_APPLICATION',
  POST_NEW_APPLICATION = 'POST_NEW_APPLICATION',
  STATUS_APPLICATION_DETAIL = 'STATUS_APPLICATION_DETAIL',
  SEE_CV = 'SEE_CV',
  //in profile
  EDIT_PROFILE = 'EDIT_PROFILE',
  SETTING = 'SETTING',
  EDIT_CONTACT = 'EDIT_CONTACT',
  EDIT_SUMMARY = 'EDIT_SUMMARY',
  EDIT_CV = 'EDIT_CV',
  EDIT_SALARY = 'EDIT_SALARY',
  //in save job

  //in message
  ROOM = 'ROOM',
}
